### ISSUE TITLE
Unity's UI Glitch

### ISSUE THREAD

**Issue by ThiPatriot** [aras-p/UnityGaussianSplatting#58] opened 2023-10-24 17:36 UTC
First of all, i have to apologize in advance if i'm wasting your time and i have to mention that i'm not a programmer or game designer and i'm just trying this plugin as a hobby. I love these new technologies and want to learn more and practice.

I have already done small projects in Unity and i know for a fact that Unity behaves completely normally even today, it is important to mention this because when i copy the repository and open it in Unity (projects/ GaussianExample), the Unity UI is just going totally crazy and i have absolutely no idea what can be causing this (since again my other Unity projects still work fine and i have imported GitHub repos of Unity projects in the past).

Again sorry if that is just a waste of time, its the first time i report an issue on GitHub and that might be caused by my material but i don't even know (i use a 3070GTX)

![Unity_4sIS7fOYZz](https://github.com/aras-p/UnityGaussianSplatting/assets/15329174/fc3af2db-288b-4810-bf78-fbfd8d3b51d7)

**Comment by aras-p** [comment] 2023-10-24 18:40
I have no idea why that would be happening. It sounds like either a GPU driver issue, or general windows issue (interaction with some 3rd party programs?), or some sort of Unity bug. I'm gonna close this since I've no idea what's the cause or how to help your situation.

**Closed by aras-p** 2023-10-24 18:40 UTC
