### ISSUE TITLE
Platforms: Does not work on Vision Pro Simulator

### ISSUE THREAD

**Issue by chihhsi** [aras-p/UnityGaussianSplatting#120] opened 2024-05-20 11:36 UTC
I was using Mac to build for `Vision Pro Simulator` and got the following error : 
`Shader error in 'Gaussian Splatting/Debug/Render Boxes': cannot assign to variable 'unity_StereoEyeIndex' with const-qualified type 'const int' at /Applications/Unity/Hub/Editor/2022.3.29f1/Unity.app/Contents/CGIncludes/UnityInstancing.cginc(187) (on metal)`
`Shader error in 'Hidden/Gaussian Splatting/Composite': cannot assign to variable 'unity_StereoEyeIndex' with const-qualified type 'const int' at /Applications/Unity/Hub/Editor/2022.3.29f1/Unity.app/Contents/CGIncludes/UnityInstancing.cginc(187) (on metal)`
`Error building Player: 2 errors`
`Build completed with a result of 'Failed' in 13 seconds (12543 ms)`
`3 errors`
`UnityEditor.EditorApplication:Internal_CallGlobalEventHandler () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:493)`
![截圖 2024-05-20 晚上7 24 23](https://github.com/aras-p/UnityGaussianSplatting/assets/125952781/7d7f8fc2-7769-4c03-9bfc-c680397c5f12)
I was using `GaussianExample-URP` project and put `GaussianSplats` and `Cube` in scene.
I was able to build for the second time, but I could only see `Cube` in `Vision Pro Simulator` and `GaussianSplats` was not seen.

Hardware Description
`Mac mini`
`M1, 2020`
`Sonoma 14.3.1`
`Macintosh HD`

Software Description
`Unity 2022.3.29f1 (Apple Silicon, LTS)`
`Xcode 15.2`
`VisionOS 1.0 (21N305 SDK)`

Thanks for help

**Comment by aras-p** [comment] 2024-05-20 12:23
This probably falls under the same "I have exactly zero VR devices around, and have spent zero time thinking about VR cases while doing this", i.e. #17. Gonna close this as duplicate of that one.

**Closed by aras-p** 2024-05-20 12:23 UTC
