### ISSUE TITLE
Platforms: does not work on Android device

### ISSUE THREAD

**Issue by zhenglin1991** [aras-p/UnityGaussianSplatting#62] opened 2023-10-30 07:07 UTC
Hi, Thanks a lot for the awesome and interesting project again.
As Unity Viewer currently only supports Windows and MacOS platform. At first, I choose MacOS platform to build Android apk in the Unity, but some issue happened, like below:

![image](https://github.com/aras-p/UnityGaussianSplatting/assets/83751361/5df32cb8-b317-49b4-87bd-b70e22067ce1)
Through checked this thread #26 , Found that this issue just happened on MacOS platform. So looked  for Windows platfrom to rebuild again. It happened below issue : 

> "Shader error in 'Gaussian Splatting/Debug/Render Boxes': no matching function for call to 'asfloat' at /zhenglin_workspace/UnityGaussianSplatting/package/Shaders/GaussianSplatting.hlsl(527) (on vulkan)"

Then I commented out below code snippet : 

https://github.com/aras-p/UnityGaussianSplatting/blob/fc97e079b04f6b1701605f9f019411ce61d49c9a/package/Shaders/GaussianSplatting.hlsl#L525-L542
 
_**Comment Out from line 527 to line 541.**_   
**Compilation Successlly on Windows** (I choose "high quality" presets to load model  at the beginning  and Vulkan as backend)

**But when run the apk on the Mobile device, the screen is black and crashed immediately.**
By the way , I tried multiple devices like HuaweiMate20 pro and Oppo Find x5. it has the same issue.  

would like to ask if anyone run it successfully on Android device or any clues is appreciated.. thank you.  

Logcat output is below:
> > 
> PowerMS : release:L=13877180,F=0x0,T="WindowManager",N=android",WS=WorkSource{10190},U=1000,P=1262
> 10-30 14:11:07.958 15313 15382 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 10-30 14:11:07.958 15313 15382 E CRASH   : Version '2022.3.12f1 (4fe6e059c7ef)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
> 10-30 14:11:07.958 15313 15382 E CRASH   : Build fingerprint: 'HUAWEI/LYA-L09/HWLYA:9/HUAWEILYA-L09/346C432:user/release-keys'
> 10-30 14:11:07.958 15313 15382 E CRASH   : Revision: '0'
> 10-30 14:11:07.958 15313 15382 E CRASH   : ABI: 'arm64'
> 10-30 14:11:07.958 15313 15382 E CRASH   : Timestamp: 2023-10-30 14:11:07.958401493+0800
> 10-30 14:11:07.958 15313 15382 E CRASH   : pid: 15313, tid: 15382, name: Thread-7  >>> com.DefaultCompany.UnityGaussianSplatting <<<
> 10-30 14:11:07.958 15313 15382 E CRASH   : uid: 10190
> 10-30 14:11:07.958 15313 15382 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr --------
> 10-30 14:11:07.958 15313 15382 E CRASH   : Cause: null pointer dereference
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x0  0000007be0ccc220  x1  0000007be0fc4600  x2  0000007c13bd8020  x3  0000000000010000
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x4  0000007b606e4e38  x5  0000007b5f8107a0  x6  00000000001c4774  x7  0000000000000000
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x8  0000000000000001  x9  0000000000000000  x10 0000000000000080  x11 0000007be0ccc230
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x12 0000000000000001  x13 0000000000000000  x14 0000007c1382ee10  x15 0000007c13bd43b8
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x16 0000007c190723b8  x17 0000007cbeea1df0  x18 0000000000000001  x19 0000000000000001
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x20 0000007c13bd8180  x21 0000007be0cd4938  x22 0000007c13bd8140  x23 0000007be0cc55c0
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x24 0000007be0ccc220  x25 0000007be0cd48d0  x26 0000007c13bd8020  x27 0000000000010000
> 10-30 14:11:07.958 15313 15382 E CRASH   :     x28 0000000000000000  x29 0000000000000000
> 10-30 14:11:07.958 15313 15382 E CRASH   :     lr  0000007c18e118d4  sp  0000007c13bd8000  pc  0000007c18dc8f18  pst 0000000080000000
> 10-30 14:11:07.958 15313 15382 E CRASH   : 
> 10-30 14:11:07.958 15313 15382 E CRASH   : backtrace:
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #00 pc 0000000000601f18  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #01 pc 000000000064a8d0  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #02 pc 000000000071c9b8  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #03 pc 000000000071538c  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #04 pc 00000000007150d4  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #05 pc 000000000036a85c  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (BuildId: ad9c4a3136038478)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #06 pc 0000000000083588  /system/lib64/libc.so (__pthread_start(void*)+36) (BuildId: 3326eee918b5ef1dbb5d558ca672e8e5)
> 10-30 14:11:07.958 15313 15382 E CRASH   :       #07 pc 00000000000241dc  /system/lib64/libc.so (__start_thread+68) (BuildId: 3326eee918b5ef1dbb5d558ca672e8e5)
> 10-30 14:11:08.113 15313 15382 E CRASH   : Forwarding signal 11
> --------- beginning of crash
> 10-30 14:11:08.114 15313 15382 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x84 in tid 15382 (Thread-7), pid 15313 (ussianSplatting)
> 10-30 14:11:08.179 15457 15457 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
> 10-30 14:11:08.179   824   824 I /system/bin/tombstoned: received crash request for pid 15382
> 10-30 14:11:08.180 15457 15457 I crash_dump64: performing dump of process 15313 (target tid = 15382)
> 10-30 14:11:08.185 15457 15457 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 10-30 14:11:08.185 15457 15457 F DEBUG   : Build fingerprint: 'HUAWEI/LYA-L09/HWLYA:9/HUAWEILYA-L09/346C432:user/release-keys'
> 10-30 14:11:08.185 15457 15457 F DEBUG   : Revision: '0'
> 10-30 14:11:08.185 15457 15457 F DEBUG   : ABI: 'arm64'
> 10-30 14:11:08.185 15457 15457 F DEBUG   : Happend: 'Mon Oct 30 14:11:08 2023
> 10-30 14:11:08.185 15457 15457 F DEBUG   : '
> 10-30 14:11:08.185 15457 15457 F DEBUG   : SYSVMTYPE: Art
> 10-30 14:11:08.185 15457 15457 F DEBUG   : APPVMTYPE: Art
> 10-30 14:11:08.185 15457 15457 F DEBUG   : pid: 15313, tid: 15382, name: Thread-7  >>> com.DefaultCompany.UnityGaussianSplatting <<<
> 10-30 14:11:08.185 15457 15457 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x84
> 10-30 14:11:08.185 15457 15457 F DEBUG   : Cause: null pointer dereference
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x0  0000007be0ccc220  x1  0000007be0fc4600  x2  0000007c13bd8020  x3  0000000000010000
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x4  0000007b606e4e38  x5  0000007b5f8107a0  x6  00000000001c4774  x7  0000000000000000
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x8  0000000000000001  x9  0000000000000000  x10 0000000000000080  x11 0000007be0ccc230
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x12 0000000000000001  x13 0000000000000000  x14 0000007c1382ee10  x15 0000007c13bd43b8
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x16 0000007c190723b8  x17 0000007cbeea1df0  x18 0000000000000001  x19 0000000000000001
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x20 0000007c13bd8180  x21 0000007be0cd4938  x22 0000007c13bd8140  x23 0000007be0cc55c0
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x24 0000007be0ccc220  x25 0000007be0cd48d0  x26 0000007c13bd8020  x27 0000000000010000
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     x28 0000000000000000  x29 0000000000000000
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     sp  0000007c13bd8000  lr  0000007c18e118d4  pc  0000007c18dc8f18
> 10-30 14:11:08.185 15457 15457 F DEBUG   : 
> 10-30 14:11:08.185 15457 15457 F DEBUG   : backtrace:
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     #00 pc 0000000000600f18  /data/app/com.DefaultCompany.UnityGaussianSplatting-tkfGe42b1l-hAft9QYVmuA==/lib/arm64/libunity.so (offset 0x1f7000)
> 10-30 14:11:08.185 15457 15457 F DEBUG   :     #01 pc 0000000000000100  <unknown>
> 10-30 14:11:08.451   809   886 D AwareLog: iawared: WorkingsetProcessCommand subCmd = 357, userId=10190, pid=15313, com.DefaultCompany.UnityGaussianSplatting
> 10-30 14:11:08.452   809   886 D AwareLog: iawared: WorkingsetPauseCollect com.DefaultCompany.UnityGaussianSplatting
> 10-30 14:11:08.513  9156  9156 E adbd    : failed to connect to socket 'localabstract:renderdoc_39920': Connection refused
> 10-30 14:11:08.589  1262 15460 W ActivityManager:   finishTopCrashedActivityLocked Force finishing activity com.DefaultCompany.UnityGaussianSplatting/com.unity3d.player.UnityPlayerActivity
> 
> > 10-30 14:11:08.589   824   824 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
> > 10-30 14:11:08.590  1262 15460 V ActivityManager: positionChild stackId=0 to top.
> > 10-30 14:11:08.591   823  3427 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
> > 10-30 14:11:08.591  1262  1347 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
> > 10-30 14:11:08.592  1262  1340 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{c8e300c u0 com.DefaultCompany.UnityGaussianSplatting/com.unity3d.player.UnityPlayerActivity}
> > 10-30 14:11:08.595  1262  1340 W ActivityManager: Skipping native crash dialog of ProcessRecord{fe717dc 15313:com.DefaultCompany.UnityGaussianSplatting/u0a190}
> > 10-30 14:11:08.600  2103  3532 E AwareLog: SPKSchedFeature: Uid has been sent, ignore.
> > 10-30 14:11:08.612  2014 15269 I BoosterSwitchP: notifyUidState do nothing
> > 10-30 14:11:08.612  2014 15269 I DeepNoDisturbP: notifyUidState
> > 10-30 14:11:08.612  2014 15269 I BrowserChrP: notifyUidState

**Comment by aras-p** [comment] 2023-10-30 08:23
This sounds like a duplicate of #26 i.e. "does not work on mobile". I did exactly zero mobile testing or effort so far, so yes very likely that it does not. Thanks for the logs, will look at them once I start to look into mobile support.

**Closed by aras-p** 2023-10-30 08:23 UTC
