### ISSUE TITLE
IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 19.

### ISSUE THREAD

**Issue by YIXIN-M** [aras-p/UnityGaussianSplatting#106] opened 2024-03-28 18:53 UTC
![Uploading mmexport1711651974538.png…]()
![Uploading mmexport1711651967553.png…]()

**Comment by aras-p** [comment] 2024-03-28 19:48
Looks like duplicate of #105 105

**Comment by YIXIN-M** [comment] 2024-03-30 05:10
thanks

**Closed** 2024-11-28 08:56 UTC
