### ISSUE TITLE
The abnormal behavior on different Android devices.

### ISSUE THREAD

**Issue by busiyg** [aras-p/UnityGaussianSplatting#131] opened 2024-08-10 08:57 UTC
Hello, thank you for your great work. We can view 3DGS in Unity, and I'm trying to deploy the project to Android devices. Currently, I'm encountering some issues. I'm using Vulkan, and I have two Android devices that are exhibiting different abnormal behaviors.

1.The first device is an Android tablet running Android 14 with Qualcomm Snapdragon 870. The project runs on this device without any errors, but nothing appears on the screen. I've checked some values at the end of the GaussianSplatRenderer.SortPoints function.

![image](https://github.com/user-attachments/assets/9b3ecc67-f3ac-4b07-bca3-275fb3fd27ae)
2.I installed the same APK on the Quest Pro, and while there is content displayed, it doesn't look right. Additionally, the ellipsoids decrease as the viewing angle changes, but if the viewing angle remains stationary, they do not decrease.

https://github.com/user-attachments/assets/45cf8a5f-0b1b-47e8-a6f6-ea34cd173ee9

**Comment by busiyg** [comment] 2024-08-10 08:59
Does anyone have any suggestions? I can provide more debugging information if needed. At the moment, I suspect there might be some issues with GPUSorting, but I'm not sure what to do about it.

**Comment by aras-p** [comment] 2024-08-10 19:15
GPU sorting issues sounds like a duplicate of #112

**Closed by aras-p** 2024-08-10 19:15 UTC
